### ISSUE TITLE
Working PWM for ESC

### ISSUE THREAD

**Issue by len0rd** [rosflight/airbourne_f4#2]
Absolutely no ideas on this yet, but will probably combine ideas from Breezy's pwm driver and and [AQ32Plus pwm esc driver](https://github.com/jihlein/AQ32Plus/blob/master/src/drv/drv_pwmEsc.c)

**Comment by superjax** [comment]
You might also want to take a look at my driver for the F1  https://github.com/superjax/airbourne/blob/master/src/pwm.cpp

**Comment by len0rd** [comment]
Tested with logic analyzer and motor on all pwm outputs. Working!

Only little quirk is output3/TIM9 is very out of phase with the others, but this doesnt really matter:

![pwm_chn_phase](https://user-images.githubusercontent.com/15990762/29581431-761afaf0-8736-11e7-8b52-9e64e677cc03.png)

**Comment by len0rd** [comment]
tested on a couple servos and motors/escs at 50 and 490 Hz respectively. Also used logic analyzer to check for proper values. Looks good to go!

**Comment by superjax** [comment]
Awesome!  Thanks Man!
