### ISSUE TITLE
Install drivers on Nvidia TX2 for USB communication

### ISSUE THREAD

**Issue by dallinbriggs** [rosflight/airbourne_f4#33]
If you want to use the VCP and communicate with an f4 board over USB, you need ACM drivers for the TX2. This video shows you how to install the CDC and ACM drivers required on the TX2. 
https://www.youtube.com/watch?v=tDZF7ntLbxc
Updated: https://www.youtube.com/watch?v=80c5j0rSN_0
Full article at Jetson hacks: http://www.jetsonhacks.com/2018/03/22/build-kernel-modules-nvidia-jetson-tx2-2/

**Comment by superjax** [comment]
Thanks man!  This is super helpful

**Comment by dpkoch** [comment]
We should add this to the documentation when we release the F4
