### ISSUE TITLE
Async I2C

### ISSUE THREAD

**Issue by superjax** [rosflight/airbourne_f4#4]

**Comment by len0rd** [comment]
Also, @superjax just a note, the hmc5883l.h from the original [airbourne library](https://github.com/superjax/airbourne/blob/master/include/hmc5883l.h), has a few incorrect register addresses. At least per [this](http://www.jameco.com/Jameco/Products/ProdDS/2150248.pdf) doc:

[HMC58X3_STATUS](https://github.com/superjax/airbourne/blame/master/include/hmc5883l.h#L13) = 0x09
Then the other ID registers (ID1,2,3) are off by one as well.

**Comment by superjax** [comment]
Oh, thanks!

**Comment by superjax** [comment]
Done!
